theme = "onedark"
[editor]
idle-timeout = 100
line-number = "relative"
auto-save = true
file-picker = { hidden = false, git-exclude = false }
cursor-shape = { insert = "bar", normal = "block" }
color-modes = true
indent-guides = { render = true }
[editor.gutters]
line-numbers = { min-width = 1 }
[editor.lsp]
display-inlay-hints = true
display-messages = true
[editor.statusline]
right = [
  "version-control",
  "workspace-diagnostics",
  "position",
  "position-percentage",
  "register",
]
[keys.normal]
C-T = ":o todo.md"
space = {q = ":bc"}
[keys.normal."C-w"]
C-o = ":o ~/.config/helix/languages.toml"
C-s = ":config-open"
C-r = ":config-reload"
[keys.insert]
"C-." = "signature_help"
# [keys.normal."\\"]
#g = ":sh tmux neww lazygit"
#"ret" = ":sh tmux split -h"
#"]" = ":sh tmux split"
#f = ":sh tmux neww ranger"
#c = ":sh tmux split -h 'cargo check --workspace ;read '"
#t =  ":sh tmux split -h 'cargo test --workspace -- --nocapture ;read '"
#[keys.normal]
#Q = ":buffer-close"
#C-p = "file_picker"
#"space" = { "space" = "command_palette"}
#C-b = "buffer_picker"
#g = { t = "goto_type_definition" }
#"#" = "goto_last_accessed_file"
#"G" = "goto_last_line"
#C-j = "goto_next_diag"
#C-k = "goto_prev_diag"
#[keys.insert]
#"C-space" = "completion"
