[[block]]
block="temperature"
collapsed=false
format="{average}"
[[block]]
block="uptime"
[[block]]
block="cpu"
format = "{barchart} {utilization} {frequency}"
[[block]]
block="net"
# use_bits=true
format = "{ip} {speed_down*_b} {speed_up*_b}"
[[block]]
block="sound"
[[block]]
block="battery"
format="{time} {percentage}"
[[block]]
block="time"
format="%d/%m %a %I:%M %P"
