unstable_features = true
imports_layout = "HorizontalVertical"
hard_tabs = true
reorder_imports = true
imports_granularity = "Crate"
brace_style = "AlwaysNextLine"
# force_multiline_blocks = true
# reorder_impl_items     = true
# indent_style           = "Block"
# empty_item_single_line = false
# fn_single_line = true
# fn_args_density = "compressed"
# report_todo            = "Always"
# report_fixme            = "Always"
