set prefix C-q
unbind-key C-b
bind-key C-q send-prefix
# set default-terminal "screen-256color-bce"
set-environment -g 'TERM' 'alacritty'
set escape-time 10
set history-limit 90000
set mode-keys vi
# set default-shell /opt/homebrew/bin/fish
# set default-command fish
unbind r
unbind '"'
unbind %
unbind c
bind c new-window -c "#{pane_current_path}"
bind '"' split-window -c "#{pane_current_path}"
bind % split-window -h -c "#{pane_current_path}"
set automatic-rename on
set automatic-rename-format '#{b:pane_current_path}'
bind r source-file ~/.tmux.conf \; display "Reloaded!"
bind j select-pane -D
bind k select-pane -U
bind h select-pane -L
# set status-bg colour8
# set status-fg colour1
bind  -r J resize-pane -D 5
bind  -r K resize-pane -U 5
bind  -r L resize-pane -R 5
bind  -r H resize-pane -L 5
set status on
set status-right '%a %h-%d %H:%M'
# set status-right-length 100
set status-left ''
set mouse on
set status-justify centre
# One Dark theme for tmux status bar
set status-style bg='#282C34',fg='#ABB2BF'
set status-left-style bg='#61AFEF',fg='#282C34'
set status-right-style bg='#61AFEF',fg='#282C34'
set pane-border-style fg='#282C34'
set pane-active-border-style fg='#ABB2BF'
set status-position top


# set @plugin 'tmux-plugins/tpm'
# set @plugin 'tmux-plugins/tmux-copycat'
# set @plugin 'tmux-plugins/tmux-yank'
# set @plugin 'tmux-plugins/tmux-open'
# set @plugin 'tmux-plugins/tmux-sensible'
set-environment -g PATH "/opt/homebrew/bin:/usr/local/bin:/bin:/usr/bin"
# run '~/.tmux/plugins/tpm/tpm'
